name: Test
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      matrix:
        php: ['7.3', '5.6']
        wp: ['*', 'dev-nightly']
      fail-fast: false
    name: WP ${{ matrix.wp }} / PHP ${{ matrix.php }}
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Composer cache
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache
        key: ${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

    - name: PHPCS cache
      if: matrix.php == '7.3' && matrix.wp == '*'
      uses: actions/cache@v1
      with:
        path: tests/cache
        # This uses the hash of query-monitor.php in its cache key because Actions doesn't support
        # always pulling in a cache file and simultaneously always updating it, unlike Travis.
        # This way we always pull in a cache file and refresh it with each new version of QM.
        key: ${{ matrix.php }}-phpcs-${{ hashFiles('query-monitor.php') }}

    - name: Install PHP
      uses: shivammathur/setup-php@2.7.0
      with:
        php-version: ${{ matrix.php }}
        extensions: mysqli, xmlwriter
        coverage: none
      env:
        fail-fast: true

    - name: Debugging
      run: |
        php --version
        php -m
        composer --version
        mysql --version

    - name: Composer validate
      if: matrix.php == '7.3' && matrix.wp == '*'
      run: composer validate --strict

    - name: Install dependencies
      run: |
        sudo systemctl start mysql.service
        composer install --prefer-dist --no-suggest
        composer require --dev --update-with-dependencies --no-suggest --prefer-dist roots/wordpress="${{ matrix.wp }} || *" wp-phpunit/wp-phpunit="${{ matrix.wp }} || *"

    - name: Run code sniffer
      if: matrix.php == '7.3' && matrix.wp == '*'
      run: |
        composer require staabm/annotate-pull-request-from-checkstyle="^1.4"
        composer test:cs2pr

    - name: Run unit tests
      run: composer test:ut
      env:
        MYSQL_DATABASE: wordpress
        WP_TESTS_DB_PASS: root
